name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main
      - rocky-8
      - rocky-9

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy with Metadata
        run: |
          # Safely escape the commit message for JSON.
          MESSAGE=$(echo "${{ github.event.head_commit.message }}" | awk 'NR==1{printf "%s", $0; next} {printf "\\n%s", $0}' | sed -e 's/\\/\\\\/g' -e 's/"/\"/g')

          # Prepare the JSON payload, including the gitSource to specify what to build.
          JSON_PAYLOAD=$(cat <<EOF
          {
            "name": "docs.rockylinux.org",
            "gitSource": {
              "type": "github",
              "repoId": "${{ secrets.VERCEL_APP_REPO_ID }}",
              "ref": "main"
            },
            "target": "production",
            "meta": {
              "contentRepo": "${{ github.repository }}",
              "contentCommitRef": "${{ github.ref_name }}",
              "contentCommitSha": "${{ github.sha }}",
              "contentCommitMessage": "$MESSAGE",
              "contentCommitLink": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
            }
          }
          EOF
          )

          # Trigger the deployment by calling the Vercel API with the JSON payload
          curl -X POST "https://api.vercel.com/v13/deployments?teamId=${{ secrets.VERCEL_TEAM_ID }}&projectId=${{ secrets.VERCEL_PROJECT_ID }}" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD"
