# V1: Simple Deploy Hook
# Triggers vercel builds 

name: Trigger Vercel Deploy - main branch

on:
  push:
    branches:
      - main
      - rocky-8
      - rocky-9

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
